#!/bin/sh

CAT=cat

for OPT ; do
	case "$OPT" in
		--)
			shift
			break
			;;
		-s|--strip-comments)
			shift
			CAT=strip_comments
			;;
		*)
			break
			;;
	esac
done

strip_comments() {
	sed 's/^[[:space:]][[:space:]]*//;/^#/d;/^$$/d;/^$/d' -- "$@"
}

$CAT "$@" | od -An -v -tx1 | sed 's/\([0-9a-fA-F][0-9a-fA-F]\)/0x\1,/g;$s/, *$//'
